### ISSUE TITLE
Enable option hash not being obeyed

### ISSUE THREAD

**Issue by pmyjavec** [tmatilai/vagrant-proxyconf#104]
I'm having some issues with disabling the Docker proxy config. As per the documentation the following is still restarting Docker inside my EL 6 vagrant machine. 

This is causing  me some hell as there some issues when restarting the Docker process and running containers on EL6. 

To disable Docker configuration I'm setting the following in my `Vagrantfile`

`
config.proxy.enabled = { svn: false, docker: false }
`

**Comment by otahi** [comment]
Sorry for inconvenient. This is not released yet and @tmatilai will release in near future. Please use develop version if you need now. See [wiki page](https://github.com/tmatilai/vagrant-proxyconf/wiki).

**Comment by tmatilai** [comment]
The future is here! ;)
[Version 1.5.0](https://github.com/tmatilai/vagrant-proxyconf/blob/master/CHANGELOG.md#150--2015-01-15) has just been released, you can upgrade to it with `vagrant plugin install vagrant-proxyconf`. It might also fix your restart issues via #92.

The README in this repository always follows the development version. The documentation for the latest release can be found in http://tmatilai.github.io/vagrant-proxyconf/

**Comment by otahi** [comment]
@tmatilai Thank you!!!
