### ISSUE TITLE
proxy config should have app specific proxy settings

### ISSUE THREAD

**Issue by kulkarni-bhaskar** [tmatilai/vagrant-proxyconf#107]
The global http_proxy configuration param sets proxies for all , 
Is it possible to specify proxy only for specific application, Lets say jus for apt and nothing else

**Comment by tmatilai** [comment]
@kulkarni-bhaskar, sure! The apt proxy config is actually the reason why this plugin was born, see fgrehm/vagrant-cachier#19. =)

For example:
```ruby
config.apt_proxy.http = "http://myproxy.example.com:3142"
```
