### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by fowlie** [tmatilai/vagrant-proxyconf#108]
Hi, I've just installed Vagrant 1.7.2, and ran `vagrant plugin install vagrant-proxyconf`. I then got this error:

```
C:\Users\webshop>vagrant plugin install vagrant-proxyconf
Installing the 'vagrant-proxyconf' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing json (1.8.2), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.2'` succeeds before bundling.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension
.

    "C:/Program Files (x86)/HashiCorp/Vagrant/embedded/bin/ruby.exe" extconf.rb

creating Makefile

make "DESTDIR="
generating generator-i386-mingw32.def
/bin/sh: -c: line 0: syntax error near unexpected token `x86'
/bin/sh: -c: line 0: `/C/Program\ Files\ (x86)/HashiCorp/Vagrant/embedded/bin/ru
by -e "puts 'EXPORTS', 'Init_generator'"  > generator-i386-mingw32.def'
make: *** [generator-i386-mingw32.def] Error 2


Gem files will remain installed in C:/Users/webshop/.vagrant.d/gems/gems/json-1.
8.2 for inspection.
Results logged to C:/Users/webshop/.vagrant.d/gems/gems/json-1.8.2/ext/json/ext/
generator/gem_make.out
```

I can't find any help with google, and this error message is very confusing for someone new to dem/bundler. Any help please?

Thanks

**Comment by tmatilai** [comment]
Hi Mats,

vagrant-proxyconf (nor Vagrant) doesn't depend on the json gem (which is only needed in Ruby 1.8, while Vagrant bundles 2.0), so it has to come from another plugin you have installed. Try uninstalling other plugins from `vagrant plugin list` to find the one to blame. =)

**Comment by fowlie** [comment]
That makes sense. The odd thing is that the only steps I did was to install VirtualBox, then Vagrant and that's it. I have done no configs/hacking, and haven't installed any other plugins. If I run `vagrant plugin list` I get this:

C:\Users\webshop>vagrant plugin list
vagrant-share (1.1.3, system)

**Comment by tmatilai** [comment]
Oh, that for sure is strange. vagrant-proxyconf doesn't have any dependencies, so I really don't understand where that json gem comes from...

But anyway, looking at the error message it seems that the issue might be the space in the installation path.

**Comment by fowlie** [comment]
You're right, uninstalling and installing Vagrant again in a different path withouth the space solved the problem. Thanks a lot for helping out :smiley:

**Comment by tmatilai** [comment]
No prob, good you got it solved. But the json gem remains a mystery. =)
