### ISSUE TITLE
Escaping $ in proxy passwords

### ISSUE THREAD

**Issue by ovidiubuligan** [tmatilai/vagrant-proxyconf#113]
there seams to be a problem with $ sign in passwords.
I have a proxy url like `http://foo:B$R@myhost:123` and after boot  the proxyes are set up correctly for apt but not for environment variables . if i do a `printenv | grep` i get `http://foo:B$@myhost:123`
I think they need to be escaped somehow .

Escaping with `\\` like so `http://foo:B\\$R@myhost:123` will make environment variables work but not apt.
Can I work around this somehow ?

**Comment by otahi** [comment]
Hi @ovidiubuligan, 

Just a work around.

> Escaping with \\ like so http://foo:B\\$R@myhost:123 will make environment variables work but not apt.

I have not tested on my environment, but how about following work around.

```ruby
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.proxy.http  = "http://foo:B\\$R@myhost:123/"
  config.proxy.https = "http://foo:B\\$R@myhost:123/"
  config.apt_proxy.http = "http://foo:B$R@myhost:123/"
  config.apt_proxy.https = "http://foo:B$R@myhost:123/"
end
```

You can override proxy servers for apt. See [Configurable applications](https://github.com/tmatilai/vagrant-proxyconf#configurable-applications)

**Comment by ovidiubuligan** [comment]
Yes , it seams to be enough . Thank you !

**Comment by otahi** [comment]
This is solved.
Ref #130.
