### ISSUE TITLE
Missing HTTPS_PROXY for Docker

### ISSUE THREAD

**Issue by Diaoul** [tmatilai/vagrant-proxyconf#116]
See here: https://github.com/tmatilai/vagrant-proxyconf/blob/master/lib/vagrant-proxyconf/action/configure_docker_proxy.rb#L75-L90

**Comment by Diaoul** [comment]
Nevermind, that doesn't seem necessary for docker to pull images properly. Somehow I thought it was used when building docker images (for example apt-get inside a Dockerfile which vagrant has to build) but it seems for that I have to send the env variables to the containers manually.

Am I correct?

**Comment by otahi** [comment]
I think you are correct.

I think `http_proxy` is enough to use https docker repository outside proxy. See [docker func newClient](https://github.com/docker/docker/blob/master/registry/registry.go#L48). And a docker container is separated from its host. If you need to use proxy environment variables on docker containers, you need to send them manually.

**Comment by Diaoul** [comment]
Thanks
