### ISSUE TITLE
Permission denied error on Windows 7

### ISSUE THREAD

**Issue by amitoj** [tmatilai/vagrant-proxyconf#119]
Hi,

Trying to install 'vagrant-proxyconf' plugin on Windows 7 machine resulting in following error message

```
Installing the 'vagrant-proxyconf' plugin. This can take a few minutes...
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Permission denied - connect(2) (Errno::EAC
CES)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/net/http.rb:878:in `open'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/net/http.rb:877:in `connect'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/net/http.rb:857:in `start'
...
...

```

Thanks,
Amitoj

**Comment by tmatilai** [comment]
Hi @amitoj,

Sorry for not responding. :(

You did'n include full stack dump, but I guess you are missing `HTTP_PROXY` and/or `HTTPS_PROXY` environment variables on the host machine, so Vagrant itself can't connect to RubyGems to download the plugin. So either set the variables, or download the plugin manually from https://rubygems.org/gems/vagrant-proxyconf and then install it with:

    vagrant plugin install path/to/downloaded/vagrant-proxyconf-x.y.z.gem
