### ISSUE TITLE
Dump proxy config after vagrant-halt or vagrant-suspend events?

### ISSUE THREAD

**Issue by JELaVallee** [tmatilai/vagrant-proxyconf#132]
I may fork/PR this as the situation just bit me hard when I found out that a user of a box I had provisioned about 6 months ago, was able to see my old credentials that were set by vagrant-proxyconf despite my having added a custom shellscript provisioning step to find/purge all config-points, apparently I missed a couple... sigh.

So, here's the suggestion/idea:

Add Vagrant::hooks  for the `::GracefulHalt` and effectively reverse all the proxy config touch points and flush an affected env-vars.  Could find any work on this having been done from a quick review of issues/forks/code.  Is this something on the plugin roadmap?

**Comment by tmatilai** [comment]
Well, to be honest this has never been an issue for me. I've always built the shared boxes with Packer (or  veewee), where setting and clearing the proxies has been done with provisioners. And normally I just share minimal base boxes and provisioning is done via Vagrantfile by users.

That said, I'm fine adding the said feature to vagrant-proxyconf, but I feel we should keep the current behaviour the default, and clean-up would only be triggered with some configuration setting. So if you get to implement it, please send a PR.

**Comment by codylane** [comment]
Couldn't find a supporting pull request and this issue should be addressed as of the 2.0.1 release.
