### ISSUE TITLE
domain_name dependencies conflict on 1.9.7

### ISSUE THREAD

**Issue by anselmhou** [tmatilai/vagrant-proxyconf#161]
Hi,

After upgrading my vagrant version to 1.9.7, I found vagrant-proxyconf is throwing errors: `Error message given during initialization: Unable to resolve dependency: user requested 'vagrant-proxyconf (> 0)'`

So I have run `vagrant plugin expunge --reinstall` that gives me the same error as `vagrant plugin install vagrant-proxyconf`.

It seems the gem dependencies on vagrant 1.9.7 is not compatible with the ones using by the plugin: 

```
> vagrant plugin install vagrant-proxyconf
Installing the 'vagrant-proxyconf' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies domain_name (= 0.5.20160615) and domain_name (= 0.5.20170404)
  Activated domain_name-0.5.20170404
  which does not match conflicting dependency (= 0.5.20160615)

  Conflicting dependency chains:
    domain_name (= 0.5.20170404), 0.5.20170404 activated

  versus:
    domain_name (= 0.5.20160615)

  Gems matching domain_name (= 0.5.20160615):
    domain_name-0.5.20160615


> vagrant -v
Vagrant 1.9.7
```

By chance any body have any idea how-to resolve this kind of error?

Thanks you in advance.

**Comment by mpepping** [comment]
Same for me .. broke after upgrading to vagrant 1.9.7 .. running `vagrant plugin repair` and `vagrant plugin expunge` doesn't help either. 

What worked for me is:

1. uninstall vagrant
2. delete ~/.vagrant.d folder
3. install vagrant 1.9.7
4. vagrant plugin install vagrant-proxyconf

**Comment by tmatilai** [comment]
I don't think this error is something we can fix in this plugin, as it does not have any external dependencies.  That `domain_name` gem is transitive dependency of Vagrant itself, so probably some issue with Vagrant's bundler cache or alike.

So I'm going to close this issue, until someone can show how we could fix the problem here.
