### ISSUE TITLE
Docker proxy config doesn't work on CoreOS 1465.6.0

### ISSUE THREAD

**Issue by rlenskij** [tmatilai/vagrant-proxyconf#162]
When running vagrant with CoreOS (latest stable), it fails at
https://github.com/tmatilai/vagrant-proxyconf/blob/d2282adb553bec7319b5485e6e3ca7b562da9240/lib/vagrant-proxyconf/cap/coreos/docker_proxy_conf.rb#L18

It seems that the `src_file` is pointed to a file that doesn't exist.
https://github.com/tmatilai/vagrant-proxyconf/blob/d2282adb553bec7319b5485e6e3ca7b562da9240/lib/vagrant-proxyconf/cap/coreos/docker_proxy_conf.rb#L14

Looks like`src_file` needs to point to `/run/systemd/system/docker.service` instead.

**Comment by taqtiqa-mark** [comment]
In case it helps this is another possible location.  Not yet fully familiar with the spec and coreOS, so HTH?

https://github.com/hypriot/cluster-lab/pull/49/commits/1b6fa31615bcf79e805e930d1297505072f77730

**Comment by codylane** [comment]
Without tests, I'm not comfortable merging in changes into the code base.  Also, since this could be CoreOS version specific I'm not sure there is an easy fix.  I've personally never used CoreOS so I cannot say for certain what the correct solution is.
