### ISSUE TITLE
how can i disable this plugin?(i dont want to use proxy anymore)

### ISSUE THREAD

**Issue by darenme** [tmatilai/vagrant-proxyconf#164]
it seems this plugin has hard code some config to the VM. is there a way to disable all these?

**Comment by gavvvr** [comment]
I have the same question. I have a provisioned machine with proxy enabled.
Then I come home and do not want to use proxy anymore.
I set
> config.proxy.enabled  = false
in Vagrantfile and try vagrant reload / halt-up / provision expecting the proxy to be disabled. Unfortunately it is left enabled.

**Comment by tmatilai** [comment]
`config.proxy.enabled = false` really disables the plugin. But that means it won't do anything, and possibly already configured settings stay intact.

What you want is to set the *value* of the settings to `false`, e.g. `config.proxy.http = false`. 

This is all somehow explained in the readme. If you have ideas how to improve the documentation, please do so! =)

**Comment by gavvvr** [comment]
Thank you! I just found it in another issue https://github.com/tmatilai/vagrant-proxyconf/issues/146#issuecomment-199849384

I think the documentation is good. Just did not read it carefully.

**Comment by darenme** [comment]
thank you guys!
