### ISSUE TITLE
vagrant-proxyconf 1.5.2 not found in vagrant 2.1.3 

### ISSUE THREAD

**Issue by CesarBallardini** [tmatilai/vagrant-proxyconf#173]
With Vagrant 2.1.3 `Vagrant.has_plugin?("vagrant-proxyconf")` returns false

Changed back to Vagrant 2.1.2 and plugin is working.

**Comment by tmatilai** [comment]
Is this still an issue? I think I saw some fix for this in the Vagrant itself.

**Comment by CesarBallardini** [comment]
Vagrant 2.1.5 is working
