### ISSUE TITLE
There is a problem with judgment of docker version

### ISSUE THREAD

**Issue by satodoc** [tmatilai/vagrant-proxyconf#197]
`/etc/docker/config.json` will not be set if the major version is 18 or more and the minor version is less than 7 because there is a problem in the following judgment.

https://github.com/tmatilai/vagrant-proxyconf/blob/master/lib/vagrant-proxyconf/action/configure_docker_proxy.rb#L200

Is not the correct judgment below?
```
return true if major >= 17 && minor >= 7 || major > 17
```

**Comment by codylane** [comment]
Hi @satodoc - Thank you for reporting this issue, you are correct that there is a logic flaw here.  I'll fix this promptly and let you know when it's complete.  

Thanks again!

**Comment by codylane** [comment]
Release 2.0.4 with fixes.  I'll leave this issue open for a few days and if there is no response i'll close this out.  Thanks again for reporting.

https://rubygems.org/gems/vagrant-proxyconf/versions/2.0.4

**Comment by satodoc** [comment]
@codylane Thank you for your quick response.
I confirmed that it works correctly with the modified version.

**Comment by codylane** [comment]
No problem, glad to help. I appreciate you taking the time to let us know this was a problem.  Keep up the good work and happy vagranting.  :) 

Have a good day my friend.
