### ISSUE TITLE
FEATURE: Add Acquire::https::Verify-Peer and Acquire::https::Verify-Host for apt proxy

### ISSUE THREAD

**Issue by codylane** [tmatilai/vagrant-proxyconf#199]
Scenario
---------
When using debian/ubuntu based OS
AND
in an environment that terminates SSL behind a proxy,
we need the ability to set  `Acquire::https::Verify-Host` and `Acquire::https::Verify-Peer` configuration options for APT.
These settings should default to `""`.

However, when the user sets the environment variable `VAGRANT_APT_VERIFY_HOST=true` or
 `VAGRANT_APT_VERIFY_PEER=true` the following APT proxy settings should change to
`Acquire::https::Verify-Host "true";` and `VAGRANT_APT_VERIFY_PEER "true";`

See pull request: https://github.com/tmatilai/vagrant-proxyconf/pull/193

**Comment by codylane** [comment]
- [ ] When releasing this change, please make sure to give full credit to

**Comment by codylane** [comment]
Change staged in master, I'm going to try and release this change by the end of the week if there are no further outstanding issues.

**Comment by greut** [comment]
@codylane wow, thanks! I'll test that.

**Comment by greut** [comment]
It's ok :clap:. :shipit:

**Comment by codylane** [comment]
Thanks for reviewing and for confirming it's working.  I've release 2.0.5 as promised.  https://rubygems.org/gems/vagrant-proxyconf/versions/2.0.5.

I'm going to go ahead and close this out since it's released.
