### ISSUE TITLE
Add support for processing of .pac files

### ISSUE THREAD

**Issue by imavroukakis** [tmatilai/vagrant-proxyconf#46]
Support for proxy auto-configuration files would be highly useful. The PAC file is well documented ( several references in http://en.wikipedia.org/wiki/Proxy_auto-config ) but in a nutshell what would be required is for Ruby code to be able to execute Javascript. A possible candidate would be execjs -> http://rubygems.org/gems/execjs

**Comment by MatheusWebDev** [comment]
Hi,
something was done or thinking about this issue ? 
In my company the proxy uses the .pac file to config and a can't use vagrant, because don't recognize it.

**Comment by codylane** [comment]
This is not a supported feature as it stands today and one I think would be better served by an additional library. Perhaps, you can download your pac file and configure your global Vagrantfile to use the right settings? Last time I used a pac file it was a straight text file that I could browse with any standard editor.
