### ISSUE TITLE
Cannot disable yum proxy

### ISSUE THREAD

**Issue by johnbellone** [tmatilai/vagrant-proxyconf#54]
Using the following Vagrantfile (and setting the environment variables) does not seem to work:

``` ruby
Vagrant.configure('2') do |config|
  config.yum_proxy.http = false
end
```

Where the environment variables are:

``` bash
VAGRANT_HTTP_PROXY=$HTTP_PROXY
VAGRANT_HTTPS_PROXY=$HTTPS_PROXY
```

I've also tried setting `VAGRANT_YUM_HTTP_PROXY` to nil and it also does not work. Unfortunately I run into this because the image I am provisioning on is already setup with a local RedHat satellite cache for RPMs.

**Comment by pdxjohnny** [comment]
fastestmirror still causes issues https://wiki.centos.org/PackageManagement/Yum/FastestMirror says

> If you are using the default CentOS configuration, and if you are **not behind** a proxy server, fastestmirror is highly recommended.

So I think it should be disabled because we are behind a proxy server, I am still having issues with it.

```bash
sudo sed -i 's/.*enabled=.*/enabled=0/g' /etc/yum/pluginconf.d/fastestmirror.conf
```

patch #148 disables
