### ISSUE TITLE
proxy support for PHP PEAR and PECL

### ISSUE THREAD

**Issue by zeleznypa** [tmatilai/vagrant-proxyconf#68]
Please,

is it possible to add support for automatic proxy settings of PHP pecl and pear?
http://stackoverflow.com/questions/2266491/how-to-use-pear-behind-proxy

**Comment by elahd** [comment]
I need to run pear during provisioning, but vagrant-proxyconf doesn't kick in for pear until provisioning is complete. My workaround is adding the below line to my Vagrant bootstrap script:

`sudo pear config-set http_proxy $(printenv http_proxy)`

The pulls the `http_proxy` environment variable set by vagrant-proxyconf and uses it to immediately configure pear's proxy settings. This command is portable as it throws a non-fatal `config-set expects 2 or 3 parameters` error in environments without a proxy server (and therefore no set `http_proxy` variable).
