### ISSUE TITLE
Problems with manual installation / Plugin not working

### ISSUE THREAD

**Issue by kevinpapst** [tmatilai/vagrant-proxyconf#70]
Hi!

Thanks for your plugin, very much appreciated :+1: 

I have an obscure problem, which I cannot solve and like to ask for your help.
Usecase is a simple setup of a new Vagrant Linux-Guest box on a Windows machine behind a companies very restrictive proxy.

I couldn't use the default "vagrant plugin install vagrant-proxyconf" due to the proxy (even with env vars `HTTP_PROXY` and `HTTPS_PROXY` set). 
So I downloaded two different version (the https://github.com/tmatilai/vagrant-proxyconf/releases/tag/v1.2.0 and master) which both have the same problem.
Installation as suggested via wiki worked:

```
C:\HashiCorp\Vagrant\embedded\bin\gem build vagrant-proxyconf.gemspec
vagrant plugin install vagrant-proxyconf-*.gem
```

But when using "vagrant up" or "vagrant reload --provision" I always receive the message:

```
There are errors in the configuration of this machine. Please fix the following errors and try again:

Vagrant:
* Unknown configuration section 'proxy'.
```

The Vagrantfile is as simple as possible:

```
Vagrant.configure("2") do |config|
  config.vm.box = "puphpet/centos65-x64"
  config.vm.box_url = "puphpet/centos65-x64"

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http = "http://myproxyip:8080/"
  else
    raise 'ProxyConf plugin not installed!'
  end
end
```

The raise condition is never met, so the plugin seems to be loaded (just to make sure: I tried to moved the raise into the if_has_plugin clause and the provisioning stopped directly with the expected "ProxyConf plugin not installed!" message).

Here is some output using the "vagrant reload --provision --debug" flag:

```
INFO global: Vagrant version: 1.6.3
INFO global: Ruby version: 2.0.0
INFO global: RubyGems version: 2.0.14
INFO global: VAGRANT_EXECUTABLE="C:\\HashiCorp\\Vagrant\\embedded\\gems\\gems\\vagrant-1.6.3\\bin\\vagrant"
INFO global: VAGRANT_HTTPS_PROXY="\"http://myProxy:8080\""
INFO global: VAGRANT_HTTP_PROXY="\"http://myProxy:8080\""
INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="C:\\HashiCorp\\Vagrant\\embedded"
INFO global: VAGRANT_INSTALLER_ENV="1"
INFO global: VAGRANT_INSTALLER_VERSION="2"
INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
INFO global: VAGRANT_LOG="debug"
INFO global: VAGRANT_YUM_HTTP_PROXY="\"http://myProxy:8080\""
INFO global: Plugins:
INFO global:   - bundler = 1.6.2
INFO global:   - mime-types = 2.3
INFO global:   - rest-client = 1.6.7
INFO global:   - vagrant-login = 1.0.1
INFO global:   - vagrant-proxyconf = 1.3.3.dev
INFO global:   - vagrant-share = 1.1.0
```

Which tells me that the plugin is loaded, same applies for "vagrant plugin list":

```
vagrant-login (1.0.1, system)
vagrant-proxyconf (1.3.3.dev)
  - Version Constraint: 1.3.3.dev
vagrant-share (1.1.0, system)
```

I use Vagrant 1.6.3 as seen in "vagrant version":

```
Installed Version: 1.6.3
Latest Version: 1.6.3

You're running an up-to-date version of Vagrant!
```

Now being at home I tried 'vagrant plugin install vagrant-proxyconf' on my Mac and the box/plugin is working as expected. So it must be either the Windows7 environment at work or the installation method. 

Can you give me some hints on how to debug the problem?
It seems that the plugin is not loaded properly, as config.proxy is not registered as possible key.

**Comment by shriharshmishra** [comment]
runefs's approach worked for me as well.
