### ISSUE TITLE
pip doesn't recognize proxy settings

### ISSUE THREAD

**Issue by fernandojsg** [tmatilai/vagrant-proxyconf#84]
Dear all, 

I've used `vagrant-proxyconf` and it works well with apt-get without problems, but It seems it's not recognized by `pip` so I need to set it by hand like:

``` ruby
exec { "pip-install-requirements":
    command => "sudo /usr/bin/pip install --proxy http://myproxy:8080 -r $proj_dirrequirements.txt",
    tries => 2,
    timeout => 600, # Too long, but this can take awhile
    require => Package['python-pip', 'python-dev'], # The package dependecies needs to run first
    logoutput => on_failure,
 }
```

Is there any way to get it working with the plugin? Or at least access to the `config.proxy.http` variables defined on the VagrantFile ?

**Comment by sradhakrishna** [comment]
@otahi, @fernandojsg,

Am in a similar situation - pip doesn't work behind proxy in my vagrant guest. Can you please help me address this?

Where do I setup the sudo -E option? In VagrantFile?

Can you please help elaborate?

Regards,
Radha.

**Comment by fernandojsg** [comment]
Hi @sradhakrishna 
You should inlcude the ```-E``` option where you call ```pip```.

I've a ```puppet``` module for install python requirements. 
This of this file (```puppet\modules\python\manifests\init.pp```) is the following:

```python
class python {
  
    package { [ 'python', 'python-virtualenv', 'python-dev', 'python-pip', 'build-essential',
        'libxml2-dev', 'libxslt1-dev', 'python-lxml',
        'libjpeg8', 'libjpeg62-dev', 'libfreetype6', 'libfreetype6-dev' ]:
        ensure => installed,
    }

	# Let's install the project dependecies from pip
    exec { "pip-install-requirements":
        command => "sudo -E /usr/bin/pip install -r /vagrant/serverside/requirements.txt",
        tries => 2,
        timeout => 600, # Too long, but this can take awhile
        require => Package['python-pip', 'python-dev'], # The package dependecies needs to run first
        logoutput => on_failure,
    }
}
```

Note how I use a command with ```sudo -E``` to install the packages required by my webapp, defined on a .txt instead of the puppet itself.
